SELECT event_name, count(distinct customer_tracking_key) from lead_event_log           
where create_date > to_date('2018-05-10 06:00','YYYY-MM-DD HH24:MI') 
and lower(vendor_name) not like '%cap%'
--and event_name in ('LEAD_RECEIVED','LEAD_SENT','MESSAGE_ROUTED_TO_LEGACY','REQUEST_SENT_TO_ASK','FAILED_OUTBOUND_MESSAGE_REROUTED_TO_LEGACY','UNPROCESSED_REQUEST_REROUTED_TO_LEGACY',
--'ASK_RESPONSE_RECEIVED','MESSAGE_ROUTED_TO_MSI','ASK_RESPONSE_RECEIVED_FROM_MSI','ROUTER_REQUEST_RECEIVED','ROUTER_REQUEST_SENT_TO_ASK','ROUTER_RESPONSE_RECEIVED_FROM_ASK','ROUTER_RESPONSE_SENT_TO_OQS',
--'Initial State','Final State','LEAD_REJECTED','DTQ_SENDING_EMAIL_SKIPPED','EMAIL_SVC_SENT:TEASER','EMAIL_SVC_SENT:RECALL','LEGACY_CASE_PREPARED', 'CPP_SERVICE_CALL')
GROUP BY  event_name
order by 2 desc
